server:
  port: 8888   #端口
  servlet:
    context-path: /my_blog   #项目根路径
  tomcat:
    uri-encoding: UTF-8  #tomcat编码

spring:
  devtools:
    restart: #热编译
      enabled: true
      additional-paths: src/main/java
  datasource: #数据源
     url: jdbc:mysql://49.233.217.228:3306/jzfp-dev?useUnicode=true&characterEncoding=utf8&useSSL=false
     username: root
     password: XHan0121520
     driver-class-name: com.mysql.cj.jdbc.Driver
     
mybatis:
  mapper-locations: classpath:com/sxh/web/dao/mapper/*.xml
  type-aliases-package: com.sxh.web.entity
  configuration-properties:
     offsetAsPageNum: true
     rowBoundsWithCount: true
     reasonable: true
pagehelper: #分页插件配置
  autoDialect: true
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
logging:
  config: classpath:config/loggback.xml
  level:
    com:
      sxh:
        web:
          dao: DEBUG #打印mybatis执行SQL
